### ISSUE TITLE
How do I install?

### ISSUE THREAD

**Issue by peredwardsson** [athackst/vscode-ament-task-provider#1]
Hello! This looks interesting as heck. Maybe I'm blind, but I can't figure out how to install this. Please provide instructions. Thanks!

**Comment by athackst** [comment]
Great question!

This code had gotten stale -- so I've updated it and added it to the extension marketplace.

If you want to install from source, follow the directions [here](https://github.com/athackst/vscode-ament-task-provider#install-your-extension), otherwise you can grab it from the marketplace [here](https://marketplace.visualstudio.com/items?itemName=althack.ament-task-provider)

**Comment by peredwardsson** [comment]
Awesome, thank you. I found your Task commands at [your other repo](https://github.com/athackst/vscode_ros2_workspace/blob/foxy/.vscode/tasks.json), which do what I want. Really slick. Thanks for combining my favorite tools, and opening my eyes to how the linting tools work in CLI too.

**Comment by slim71** [comment]
Can I suggest adding this info in the README? I've come across the code but didn't know about the extension, which is needed to use your `task.json`too! :smile:
